### ISSUE TITLE
[Simply Dark Theme] Performance issues on user actions

### ISSUE THREAD

**Issue by Davoleo** [Gibbu/Powercord-Themes#1]
Simply Dark for Powercord is a pretty interesting theme!
But I've noticed some severe performance issues when using it.

One of which is:
- FPSdrop/lag when scrolling server and DM chats (especially when scrolling upwards)
- pretty long delay when changing channel, server, chat and when sending messages in any chat (these delays usually are about 1000ms long)

**Comment by Gibbu** [comment]
I'm thinking of a yet another rework for SimplyDark. Allowing for both Dark and Light themes and proper Powercord support as at the moment my Powercord themes just import the BetterDiscord css. Hopefully this should be soon as I am currently working on other things.

**Comment by Davoleo** [comment]
looking forward to it! :)
