### ISSUE TITLE
[Improvement] RadialStatus

### ISSUE THREAD

**Issue by barbiehunter** [Gibbu/Powercord-Themes#3]
An improvement which would be nice if the status would be also in the chat around the profile picture, so you can check the status easier I guess.

**Comment by Gibbu** [comment]
Not possible with a theme. You can use a BetterDiscord plugin named  StatusEverywhere by Zerebos.

**Comment by barbiehunter** [comment]
I would like to use it, but it have at the moment some Crash problems, thats why i ask.

**Comment by Gibbu** [comment]
You'll have to wait for Zerebos to update it then.
